---
include:
- gems/**/*.rb
exclude:
- gems/*/spec/**/*
- gems/*/test/**/*
- gems/*/vendor/**/*
- gems/*/.bundle/**/*
require: []
domains: []
reporters:
- rubocop
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
