# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in parameterized_testing-rspec.gemspec
gemspec

gem "parameterized_testing", path: "../parameterized_testing"
gem "rake", "~> 13.0", require: false
gem "rspec", "~> 3.0", require: false
gem "rubocop", "~> 1.63", require: false
gem "rubocop-rspec", "~> 2.29", require: false
